"""add unit volume and price to purchase history

Revision ID: 1e6bcbaec30b
Revises: a7a9a71b6d03
Create Date: 2025-12-01 19:08:28.031184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6bcbaec30b'
down_revision: Union[str, None] = 'a7a9a71b6d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_history', sa.Column('unit_volume', sa.String(length=100), nullable=True))
    op.add_column('purchase_history', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_history', 'unit_price')
    op.drop_column('purchase_history', 'unit_volume')
    # ### end Alembic commands ###
