"""add small_category review rating quantity to purchase_history

Revision ID: 638dda834d6e
Revises: 1e6bcbaec30b
Create Date: 2025-12-01 19:31:45.332716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638dda834d6e'
down_revision: Union[str, None] = '1e6bcbaec30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_history', sa.Column('small_category', sa.String(length=255), nullable=True))
    op.add_column('purchase_history', sa.Column('review', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('purchase_history', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('purchase_history', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_history', 'quantity')
    op.drop_column('purchase_history', 'rating')
    op.drop_column('purchase_history', 'review')
    op.drop_column('purchase_history', 'small_category')
    # ### end Alembic commands ###
