"""add unit_volume and unit_price to products

Revision ID: a7a9a71b6d03
Revises: 06ea1b13de09
Create Date: 2025-12-01 18:11:17.351511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a9a71b6d03'
down_revision: Union[str, None] = '06ea1b13de09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.add_column('products', sa.Column('unit_volume', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index('ix_purchase_history_user_id', table_name='purchase_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_purchase_history_user_id', 'purchase_history', ['user_id'], unique=False)
    op.drop_column('products', 'unit_price')
    op.drop_column('products', 'unit_volume')
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###
